### ISSUE TITLE
Just a little advanced win system

### ISSUE THREAD

**Issue by Floodo** [Ajneb97/PaintballBattle#1]
Hi :) . I really love your plugin, how its so easy to setup and modify. But I'd like to ask you, if you can add choice how the WIN will be? Like you win only if you kill other team, otherwise by ending time. But if the time ends, the team with more lives, will win. So I'm asking, if you can add choice to win instead of lives, win by kills. :) (this is not issue request, but more like impovement? ) 
Still your plugin works fine 👍 . Good job

**Comment by Ajneb97** [comment]
I won't be adding such big features on the plugin anymore, that's why I made it open source so you can add your own features.
