### ISSUE TITLE
error if I hit anyone with a snowball

### ISSUE THREAD

**Issue by derehrenputzer** [Ajneb97/PaintballBattle#7]
Hey,
The title says what it is.
My problem is when I shoot someone in the game with a snowball, an error message form serverconsol: (Paintball) This sound is not valid!

I don't know what you can do there, you don't get killed if you get shot down, that's exactly what it is.
The plugin looks very funny
MC version 1.12 spigiot

Can anyone help me?

**Comment by flechabenx** [comment]
In your config, change the name of sounds with these ones https://helpch.at/docs/1.12.2/org/bukkit/Sound.html

**Comment by Ajneb97** [comment]
In your config, change the name of sounds with these ones https://helpch.at/docs/1.12.2/org/bukkit/Sound.html

**Comment by derehrenputzer** [comment]
Thanks, now it works! a really great plugin :)
